myapp:
  build: .
  ports:
   - "8001:9000"
  links:
    - db
  environment:
    - PGHOST=db
    - PGDATABASE=postgres
    - PGUSER=postgres
    - BURNER_PASS=iAmABurner
    - HOSTNAME=http://mattpengelly.com
  volumes:
    - /var/lib/postgres

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - myapp
  links:
    - myapp:myapp

db:
  image: postgres
