db:
  image: postgres
myapp:
  build: .
  ports:
   - "8080:9000"
  links:
    - db
  environment:
    - PGHOST=db
    - PGDATABASE=postgres
    - PGUSER=postgres
    - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
