db:
  image: postgres
myapp:
  build: .
  ports:
   - "80:9000"
  links:
    - db
  environment:
    - PGHOST=db
    - PGDATABASE=postgres
    - PGUSER=postgres
    - BURNER_PASS=iAmABurner
    - HOSTNAME=http://mattpengelly.com
  volumes:
    - /var/lib/postgres
