db:
  image: postgres
  ports:
    - "5432:5432"
myapp:
  build: .
  ports:
   - "8080:9000"
  links:
    - db
  environment:
    - PGHOST=db
    - PGDATABASE=postgres
    - PGUSER=postgres
    - DATABASE_URL=postgres://postgres@db:5432/postgres
